SLMap = {0: 0.3, 1: 1, 2: 0}
adjustmentPercent = 0.3
initialPremium = 100
mtmStopLoss = 60
path = "C:\\Users\\Safwan PC\\banknifty_new\\"
index = "BANKNIFTY"
strikeDifference = 100
noOfAdjustment = 1
oneSideFullHitFlag = True