SLMap = {0: 0.3, 1: 1, 2: 0}
adjustmentPercent = 0.3
initialPremium = 60
mtmStopLoss = 30
path = "C:\\Users\\Safwan PC\\banknifty_new\\"
index = "FINNIFTY"
indexToken = "26037"
strikeDifference = 50
noOfAdjustment = 1
oneSideFullHitFlag = True